### ISSUE TITLE
Documentation updates (feature/commons)

### ISSUE THREAD

**Issue by natanlao** [ucsc-cgp/cgp-deployment#24]
https://github.com/DataBiosphere/cgp-deployment/pull/22#issuecomment-389341870
> there are a bunch of other things in the README that need to be fixed as well. For example, references to metadata-indexer, instructions to type random strings...

Also, add `boardwalk/boardwalk` to .gitignore

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/DEP-11)
┆Project Name: CGP-Deployment
┆Issue Number: DEP-11

**Comment by natanlao** [comment]
The [documentation](https://github.com/DataBiosphere/cgp-deployment#installer-question-notes) basically restates the `install_bootstrap` prompts, which I defeats the purpose of the script being interactive. I think that anything the README adds to the script should be presented when the script runs, and shouldn't be separated.

**Comment by cricketsloan** [comment]
➤ Charles Overbeck commented:

[~nalao] Your PR has been merged; can we close this bug?

**Comment by natanlao** [comment]
Closed by #28
